### PR TITLE
update list of compatible PHP versions

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Review by RichardSmedley — APPROVED** [review]
:+1:

**Review by AV25242 — COMMENTED** [review]
LGTM

**Comment by AV25242** [comment]
@RichardSmedley  when can we expect this to go ?

**Comment by RichardSmedley** [comment]
It's up on staging: https://docs-staging.couchbase.com/php-sdk/3.1/project-docs/compatibility.html
and will be in tonight's prod build....
Message me if you need it there sooner.

**Pull request merged**
